### ISSUE TITLE
An array of table values returning on get request from server

### ISSUE THREAD

**Issue by caissalover** [searx/searx-stats2#53]
Can you have an API which gives the table on searx.space online https sites in an array of array format or array of dictionary format?

It would be really helpful to find online searx instances with suitable characteristics. If you can add querying, it will be all the more better.

Thanks.

**Comment by dalf** [comment]
What about https://searx.space/data/instances.json ?

**Comment by caissalover** [comment]
Thank you very much dalf! That's exactly what I wanted.
