### ISSUE TITLE
Mention gimmeasearx

### ISSUE THREAD

**Issue by demostanis** [searx/searx-stats2#55]
I recently created [gimmeasearx](https://github.com/demostanis/gimmeasearx).
It would be great to mention it under "Meta-searx instances".

**Comment by unixfox** [comment]
Could you also provide a service on the clearnet? Not everyone uses Tor.

**Comment by demostanis** [comment]
I'd rather not provide a clear web service. People can still build and run gimmeasearx in a single command.

**Comment by unixfox** [comment]
People who visit https://searx.space are usually people that don't want to host a program (in this case Searx) by themselves so you aren't doing them a favor by forcing them to host gimmeasearx.

Anyway, feel free to add yourself into the about page by creating a new PR, it's around this line: https://github.com/searx/searx-stats2/blob/master/html/index.html#L86.

**Comment by demostanis** [comment]
Here

**Comment by maninthemiddle01** [comment]
The onion site is not found by Tor-Browser. Delete it from the "about" page?

**Comment by demostanis** [comment]
whoops, my bad, it should be back
