### ISSUE TITLE
Comment https://searx.bar

### ISSUE THREAD

**Issue by zevlee** [searx/searx-stats2#61]
Are instances in the "Offline & Error" category regularly scanned to see if they're working? If not, can you please verify if https://searx.bar is working and re-add it to the "Online HTTPS" list if so? Cryptcheck should be able to resolve the address now. That was the issue that led to Cryptcheck showing a timeout.

[Cryptcheck results](https://cryptcheck.fr/https/searx.bar)

**Comment by zevlee** [comment]
I believe that the DNS resolve error was resolved for Cryptcheck [here](https://github.com/aeris/cryptcheck/issues/54). Perhaps a similar edit to the configuration of check.searx.space would solve the issue on your end as well.

**Comment by unixfox** [comment]
The thing is that we don't use the official cryptcheck website, we launch cryptcheck manually so we aren't affected by cryptcheck.fr

**Comment by dalf** [comment]
Yesterday, I've installed unbound and cryptcheck on searx.space found an A+ grade.

The TLS grade are cached for one day, so the value will be updated today.

**Comment by zevlee** [comment]
Looks like everything is working now for searx.bar. Thank you for your help!
