### ISSUE TITLE
TLS grade not displaying correctly

### ISSUE THREAD

**Issue by TheSilkky** [searx/searx-stats2#69]
TLS grade isn't displaying for a lot of instances even though most of them would have gotten A+.
![screenshot](https://user-images.githubusercontent.com/77580166/112601536-af130600-8e66-11eb-9bd6-cc67375ed0a7.png)

Crypt check still displays correct rating though.
![screenshot2](https://user-images.githubusercontent.com/77580166/112601667-d4077900-8e66-11eb-8e87-610dcda12aec.png)

**Comment by dalf** [comment]
Thank you for the report.

It will fixed in few hours.
